### ISSUE TITLE
Demo authentication seems broken

### ISSUE THREAD

**Issue by sneko** [duyet/feedback#362]
Hi @duyet,

I'm unable to log in through email/gmail onto https://feedback.okie.one/api/auth/signin to test your product. Could you confirm this error and if it's planned to be solved?

Thank you,

**Comment by adryserage** [comment]
@sneko The same error exist in production to

> Edit : Should be resolved in #367

```
[next-auth][error][adapter_error_createUser] 
https://next-auth.js.org/errors#adapter_error_createuser Argument name for data.name is missing.
 {
  message: 'Argument name for data.name is missing.\n',
  stack: 'Error: Argument name for data.name is missing.\n' +
    '\n' +
    '    at Yn.validate (/var/task/dashboard/node_modules/@prisma/client/runtime/library.js:148:91)\n' +
    '    at Ur.createMessage (/var/task/dashboard/node_modules/@prisma/client/runtime/library.js:163:13577)\n' +
    '    at /var/task/dashboard/node_modules/@prisma/client/runtime/library.js:173:10192\n' +
    '    at runInChildSpan (/var/task/dashboard/node_modules/@prisma/client/runtime/library.js:70:25749)\n' +
    '    at t._executeRequest (/var/task/dashboard/node_modules/@prisma/client/runtime/library.js:173:10181)',
  name: 'Error'
}

```

```
prisma:query BEGIN
prisma:query SELECT "public"."VerificationToken"."token", "public"."VerificationToken"."identifier", "public"."VerificationToken"."expires" FROM "public"."VerificationToken" WHERE (("public"."VerificationToken"."identifier" = $1 AND "public"."VerificationToken"."token" = $2) AND 1=1) LIMIT $3 OFFSET $4
prisma:query SELECT "public"."VerificationToken"."token" FROM "public"."VerificationToken" WHERE (("public"."VerificationToken"."identifier" = $1 AND "public"."VerificationToken"."token" = $2) AND 1=1)
prisma:query DELETE FROM "public"."VerificationToken" WHERE ("public"."VerificationToken"."token" IN ($1) AND (("public"."VerificationToken"."identifier" = $2 AND "public"."VerificationToken"."token" = $3) AND 1=1))
prisma:query COMMIT
prisma:query SELECT "public"."User"."id", "public"."User"."name", "public"."User"."email", "public"."User"."emailVerified", "public"."User"."image", "public"."User"."createdAt", "public"."User"."updatedAt" FROM "public"."User" WHERE ("public"."User"."email" = $1 AND 1=1) LIMIT $2 OFFSET $3
prisma:query SELECT "public"."User"."id", "public"."User"."name", "public"."User"."email", "public"."User"."emailVerified", "public"."User"."image", "public"."User"."createdAt", "public"."User"."updatedAt" FROM "public"."User" WHERE ("public"."User"."email" = $1 AND 1=1) LIMIT $2 OFFSET $3
```
